### ISSUE TITLE
Support on TGI (Text Generation Inference)

### ISSUE THREAD

**Issue by muhammad-asn** [neuralmagic/guidellm#49]
In the future, is it possible for guidellm to support TGI (Text Generation Inference)?

**Comment by eldarkurtic** [comment]
Guidellm supports TGI as well, we are just missing docs. Here is how to start a TGI server (thanks to @philschmid):
https://github.com/neuralmagic/guidellm/pull/43/files

**Comment by muhammad-asn** [comment]
Awesome, thanks
